template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "russ1263"
__REPO__ = "lang-rus"
__UND2C__ = "ru"
__UNDEFINED__ = "Russian"
__UND__ = "rus"
