template = "https://github.com/giellalt/template-lang-und"
rev_id = 312
template_sha = "aaa43738ed413bb95e9bd39f5489b35bab88cc4b"

[replacements]
__GLOTTOLOG_ID__ = "russ1263"
__REPO__ = "lang-rus"
__UND2C__ = "ru"
__UNDEFINED__ = "Russian"
__UND__ = "rus"
