template = "https://github.com/giellalt/template-lang-und"
rev_id = 323
template_sha = "dfd6613f16d25eef74b592360a48496624ab327d"

[replacements]
__GLOTTOLOG_ID__ = "russ1263"
__REPO__ = "lang-rus"
__UND2C__ = "ru"
__UNDEFINED__ = "Russian"
__UND__ = "rus"
