[package]
name = "rus"
human_name = "Russian"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.rus]
filename = "ru-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-rus"
platform = "windows"
uuid = "8269141F-4C59-4038-97BC-24736F91131D"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.ru"
package = "speller-rus"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-rus-mso"
platform = "windows"
uuid = "DB5D1126-5BC7-4B3E-9ABB-2AA097239B0B"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-rus"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
